version: '3'
services:
  user-service:
    build:
      context: ../user-service
      dockerfile: Dockerfile
    image: user-service:dev
    container_name: user-service-container
    ports:
      - 8000:8000
    environment:
      - MYSQL_HOST=host.docker.internal
      - MYSQL_PORT=3307
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Kumar_123
      - MYSQL_DATABASE=users
    networks:
      - user-app
    depends_on:
      - mysql

  mysql:
    container_name: my-mysql
    image: mysql:latest
    restart: always
    ports:
      - 3307:3307
    networks:
      - user-app
    environment:
      - MYSQL_ROOT_PASSWORD=Kumar_123
      - MYSQL_DATABASE=users
    volumes:
      - mysql-data:/data/db

networks:
  user-app:
    driver: bridge
volumes:
  mysql-data:
    driver: local
