version: '3'
services:
  user-service:
    build:
      context: ../user-service
      dockerfile: Dockerfile
    ports:
      - 8000:8000

  email-service:
    build:
      context: ../email-service
      dockerfile: Dockerfile
    ports:
      - 9000:9000
