apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
      - name: user-container
        image: chamathranaweera/user-service-img:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 300
          periodSeconds: 300
          failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: user-service 
  labels:
    app: user-service
spec:
  type: ClusterIP
  selector:
    app: user-api
  ports:
  - name: user-port
    port: 80
    protocol: TCP
    targetPort: 8000