
const EMAIL_SERVICE_BASE_URL = process.env.EMAIL_SERVICE_BASE_URL
const EMAIL_SERVICE_PREFIX = process.env.EMAIL_SERVICE_PREFIX
const EMAIL_SERVICE_EMAIL_TEMPLATE = process.env.EMAIL_SERVICE_EMAIL_TEMPLATE
const EMAIL_SERVICE_FROM_EMAIL = process.env.EMAIL_SERVICE_FROM_EMAIL

module.exports = { EMAIL_SERVICE_BASE_URL, EMAIL_SERVICE_PREFIX, EMAIL_SERVICE_EMAIL_TEMPLATE, EMAIL_SERVICE_FROM_EMAIL }